[package]
edition = "2021"
name = "tonbolite"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.76"
rusqlite = { workspace = true }
wasm-bindgen = "0.2.99"
web-sys = { version = "0.3.76", features = ['console'] }
